config/routes.rb
Rails.application.routes.draw do

  root to: 'books#index'
  resources :books
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :author, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path
    else
      render :new
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to books_path
    else
      render :edit
    end
  end

  def destroy
    Book.destroy(params[:id])
    redirect_to books_path
  end

  private

    def book_params
      params.require(:book).permit(:title, :author, :completed)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>Edit book!</h1>

<%= simple_form_for @book do |f| %>
  <%= f.input :title %>
  <%= f.input :author %>
  <%= f.input :completed %>
  <%= f.button :submit %>
<% end %>

<%= link_to 'Back to Home', books_path %>

app/views/books/index.html.erb
<h1>Welcome to the Reading List App</h1>

<table>
  <thead>
    <th>Title</th>
    <th>Author</th>
    <th>Completed?</th>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.author %></td>
      <td><%= book.completed %></td>
      <td><%= link_to 'Show Book', book_path(book) %></td>
      <td><%= link_to 'Edit', edit_book_path(book) %></td>
      <td><%= link_to 'Remove', book_path(book), method: :delete %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Add New Book', new_book_path %>

app/views/books/new.html.erb
<h1>Please add a book!</h1>

<%= simple_form_for @book do |f| %>
  <%= f.input :title %>
  <%= f.input :author %>
  <%= f.button :submit %>
<% end %>

<%= link_to 'Back to Home', books_path %>

app/views/books/show.html.erb
<h1>Welcome to the Reading List App</h1>

<table>
  <thead>
    <th>Title</th>
    <th>Author</th>
    <th>Completed?</th>
  </thead>
  <tbody>
    <tr>
      <td><%= @book.title %></td>
      <td><%= @book.author %></td>
      <td><%= @book.completed %></td>
      <td><%= link_to 'Edit', edit_book_path(@book) %></td>
      <td><%= link_to 'Remove', book_path(@book), method: :delete %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Back to Home', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticeApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>